# Generated by Django 2.0.4 on 2018-04-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animal_exhibitneighbors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExhibitNeighbors',
            new_name='Neighbor',
        ),
    ]
