# Generated by Django 2.0.4 on 2018-04-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20180426_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='zoo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Zoo'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animalAtExhibit', to='zoo.Animal'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exhibit', to='zoo.Exhibit'),
        ),
    ]
