# Generated by Django 2.0.4 on 2018-04-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_auto_20180426_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit',
            old_name='animal',
            new_name='animals',
        ),
    ]
