# Generated by Django 2.0.4 on 2018-04-30 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0008_auto_20180426_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='logoFileName',
            field=models.CharField(help_text='Enter the logo file path', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='exhibit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Exhibit', to='zoo.Exhibit'),
        ),
    ]
