# Generated by Django 2.0.4 on 2018-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0009_auto_20180430_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dietDescription',
            field=models.CharField(help_text="Enter a description of the animal's diet.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='habitatDescription',
            field=models.CharField(help_text='Enter a description of the habitat.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='imageFileName',
            field=models.CharField(help_text='Enter the image file path', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='soundFileName',
            field=models.CharField(help_text='Enter the sound file path', max_length=200, null=True),
        ),
    ]
