# Generated by Django 2.0.4 on 2018-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0011_auto_20180501_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitneighbor',
            name='direction',
            field=models.CharField(blank=True, choices=[('n', 'North'), ('s', 'South'), ('w', 'West'), ('e', 'East'), ('nw', 'NorthWest'), ('ne', 'NorthEast'), ('sw', 'SouthWest'), ('se', 'SouthEast')], help_text='Enter Direction', max_length=2, null=True),
        ),
    ]
