# Generated by Django 2.0.4 on 2018-05-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0012_auto_20180501_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='animals',
        ),
    ]
