# Generated by Django 2.0.4 on 2018-05-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0013_remove_exhibit_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='dietDescription',
            field=models.TextField(blank=True, help_text="Enter a description of the animal's diet.", null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='habitatDescription',
            field=models.TextField(blank=True, help_text='Enter a description of the habitat.', null=True),
        ),
    ]
