# Generated by Django 2.0.4 on 2018-05-07 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0014_auto_20180503_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ageDescription',
            field=models.TextField(blank=True, help_text="Enter a description of the animal's average life span.", null=True),
        ),
    ]
