# Generated by Django 2.0.4 on 2018-05-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0015_animal_agedescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='soundFileName',
        ),
        migrations.AlterField(
            model_name='animal',
            name='ageDescription',
            field=models.CharField(blank=True, help_text="Enter a description of the animal's average life span.", max_length=200, null=True),
        ),
    ]
