# Generated by Django 2.0.4 on 2018-05-07 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0016_auto_20180507_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='zoo',
        ),
    ]
